import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Underdev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Underdev
        </h1>

        <p className={styles.description}>
          We are working on it, relax. 😎
        </p>
      </main>

      <footer className={styles.footer}>
        Underdev | All Rights Reserved.
      </footer>
    </div>
  )
}
